apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "documenso.fullname" . }}-browserless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "documenso.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.browserless.replicas }}
  strategy:
    type: {{ .Values.browserless.strategyType }}
  selector:
    matchLabels:
      {{- include "documenso.selectorLabelsBrowserless" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "documenso.selectorLabelsBrowserless" . | nindent 8 }}
      {{- if .Values.podAnnotations }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      volumes:
      {{- with .Values.browserless.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "documenso.fullname" . }}-browserless
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.browserless.image.repository }}:{{ .Values.browserless.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.browserless.image.pullPolicy }}
          {{- if .Values.browserless.service.enabled }}
          ports:
            - containerPort: {{ .Values.browserless.service.port }}
              name: {{ .Values.browserless.service.name }}
              protocol: {{ .Values.browserless.service.protocol }}
          {{- end }}

          volumeMounts:
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- if or ((index . "limits" | default dict).cpu | default false) ((index . "limits" | default dict).memory | default false) }}
            limits:
              {{- toYaml .limits | nindent 14 }}
            {{- end }}
            {{- if or ((index . "requests" | default dict).cpu | default false) ((index . "requests" | default dict).memory | default false) }}
            requests:
              {{- toYaml .requests | nindent 14 }}
            {{- end }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}