{{- if .Values.browserless.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.browserless.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "documenso.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "documenso.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.browserless.service.port }}
      targetPort: {{ .Values.browserless.service.name }}
      protocol: {{ .Values.browserless.service.protocol }}
      name: {{ .Values.browserless.service.name }}
{{- end }}