apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.data.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "docuseal.labels" . | nindent 4 }}
  annotations:
    everest.io/disk-volume-type: {{ .Values.persistence.data.storageType }}
spec:
  {{- $storageClass := include "docuseal.data.storageClass" . }}
  {{- if $storageClass }}
  storageClassName: {{ $storageClass }}
  {{- end }}
  accessModes: {{ include "docuseal.data.accessModes" . }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.storageSize }}
