apiVersion: v2
name: docuseal
description: A Helm chart for deploying Docuseal with Cloud native Postgres on Kubernetes
type: application
version: 1.0.2

keywords:
  - docuseal
  - stackforge
  - k8s
  - kubernetes

maintainers:
  - name: StackForge
    url: https://stack-forge.eu
    email: charts@stack-forge.cloud

home: https://stack-forge.eu

sources:
  - https://github.com/StackForge-EU/helmcharts/tree/main/charts/docuseal
