{{- if and .Values.mariadb.enabled (not .Values.mariadb.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghostcms.fullname" . }}-mariadb
  labels:
    {{- include "ghostcms.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ if .Values.mariadb.password }}{{ .Values.mariadb.password | b64enc | quote }}{{ else }}{{ randAlphaNum 16 | b64enc | quote }}{{ end }}
{{- end }}